### ISSUE TITLE
wireActor[] - proposal

### ISSUE THREAD

**Issue by pawelpanasewicz** [adamw/macwire#108]
Instead of creating actor in form of 
```
// deps ...
val aref: ActorRef = Props(wire[ActorImpl])
```

which [may lead to problems when using within the actor code](http://doc.akka.io/docs/akka/current/scala/actors.html#Dangerous_Variants) MacWire could provide such API:

```
val aref = wireActor[ActorImpl]
```

`wireActor` macro could call factory method using `Props` object instead of constructor as it is done usually. 

Such approach (not calling Actor constructor directly) is the recommended way (along akka docs) of creating actors.

Implementation of feature can be in separate project (say `macwire-akka`) with `akka` dependency in provided scope. Thanks to that  user can decide if wants to use this feature.

It's only a proposal. Let me know your opinion before someone (me ;)) starts working on it. Does it make any sense?

**Comment by pawelpanasewicz** [comment]
After some reading I think that above can be achieved by combining: [Akka's IndirectActorProducer](http://doc.akka.io/docs/akka/current/scala/actors.html#Dependency_Injection) and [wireWith](https://github.com/adamw/macwire#factory-methods). Later I try to provide working snipped here.

**Comment by adamw** [comment]
I'm not sure what's the "best" way to do this, personally I'm usually using the discouraged method of using `new` inside `Props` ;)

Maybe it would be a good idea to ask on akka-user or sth like that, what would be the recommended, type-safe (this rules out passing the `Class` and arguments) way of creating an actor with dependencies.

Btw. they also mention a macro "in the future", maybe there's a PR candidate there as well, but again, would be best to ask akka maintainers.

**Comment by ktoso** [comment]
> I'm not sure what's the "best" way to do this, personally I'm usually using the discouraged method of using new inside Props ;)

The recommendation mentioned above is mostly about stopping people from closing over dangerous things accidentally (via `=> new ...`). In fact, the "best" way is to have a companion object with `def props = Props(new Actor(blabla))`, it's also the fastest AFAIR.

Since mac-wire kind of is "close over stuff" (well, "pass them in") anyway, I don't think generating a `Props(new MyActor...)` would be unexpected.

I just noticed the docs mention we'd provide a macro... We're not working on that, must be some ancient plans there - would be awesome if macwire could provide this :-)

**Comment by ktoso** [comment]
One note, please remember to support `wireActor[BlaBla]("myname")`

**Comment by adamw** [comment]
@ktoso thanks for the info! :)
@pawelpanasewicz `wireActor` it is then

**Comment by ktoso** [comment]
Additional thoughts - please remember to support child actors as well.
Perhaps it would be better to provide it as extension methods on system and context?

```
import macwire.MacWireAkka._ // whatever the name would be

system.wireActor[Bartender]("bob")
context.wireActor[Charlie]("charlie")
```

??

**Comment by ktoso** [comment]
Even more thoughts, pulling in future things from Akka Typed already:

We always want to encourage giving actors proper names.
Nowadays it's not as strongly recommended as it could be.
In typed what we'll have is `spawnAnonymous(...)` vs. `spawn(..., name)`.

So here you could already encourage that best practice via `wireAnonymousActor` and `wireActor`.
Yeah the anonymous one is longer and uglier, on purpose, to encourage people to use the nicer one with a proper name :-)

**Comment by pawelpanasewicz** [comment]
Cool! Thanks for advices :) I'll work on it.

**Comment by ktoso** [comment]
Very cool, grats guys 👍

**Comment by pawelpanasewicz** [comment]
@ktoso thanks! Could you as well take a look at #112. Chapter [akka-integration](https://github.com/pawelpanasewicz/macwire/blob/0560ba7ec700eb99e6443fe266cb14527de662d8/README.md#akka-integration).

**Comment by saamalik** [comment]
@pawelpanasewicz  looks great! When creating child actors, how come all child actor constructor parameters (dependencies) have to be 'wired' (e.g: `val dep1 = wire[Dep]`) in into the parent actor if they were previously defined in another module? Well I guess it's a question of scope, since macwire can't determine whether the module would've even executed. However, the follow-up question is that if another module already wires in `val dep1 = wire[Dep]`, when also defining the same dependency in the parent actor, would `dep1` point to the same reference?

**Comment by pawelpanasewicz** [comment]
Hey @saamalik!
Resolving dependencies here works in the same way as standard macwire. So there are (at least) 3 options available to you in order to pass instance of `Dep` to your anonymous actor:

1. just wire it somewhere before creating nonymous actor
2. pass it as constructor parameter to the parent actor
3. pass whole module containing this `dep1` as constructor parameter to the parent actor.
