### ISSUE TITLE
Can't use multiple tags

### ISSUE THREAD

**Issue by joprice** [adamw/macwire#34]
When trying to use multiple Tags, the compile throws the error `cyclic aliasing or subtyping involving type`.

```scala
trait NonEmpty
trait Trimmed
case class (name: String @@ NonEmpty @@Trimmed)
```

**Comment by adamw** [comment]
Right, didn't try multiple tags :) That happens as `@@` adds an artifical type alias to the base class. And here we are trying to do that two times.

Either way, specifying multiple tags would be problematic as the tag order would matter, I suppose. 

Maybe something along the lines of `String @@ (Tag1 + Tag2)` would work? So that `Tag1 <: (Tag1 + Tag2)`. In other words, we would need a sum type.

**Comment by adamw** [comment]
As @mkubala  pointed out, we could just use `with` :)

That would require changing the tagging infrastructure to:

```scala
trait Tagging {
  type Tag[+U] = { type Tag <: U }
  type @@[T, +U] = T with Tag[U]
  type Tagged[T, U] = T with Tag[U]
  implicit class Tagger[T](t: T) {
    def taggedWith[U]: T @@ U = t.asInstanceOf[T @@ U]
  }
  implicit class AndTagger[T, U](t: T @@ U) {
    def andTaggedWith[V]: T @@ (U with V) = t.asInstanceOf[T @@ (U with V)]
  }
}
```

and example usage:

```scala
class Berry()
trait Black
trait Blue

lazy val blackberry2: Berry @@ (Blue with Black) = wire[Berry].taggedWith[Black].andTaggedWith[Blue]
lazy val blackberry3: Berry @@ (Black with Blue) = wire[Berry].taggedWith[Black].andTaggedWith[Blue]
lazy val blackberry4: Berry @@ Black = wire[Berry].taggedWith[Black].andTaggedWith[Blue]
lazy val blackberry5: Berry @@ Blue = wire[Berry].taggedWith[Black].andTaggedWith[Blue]
lazy val blackberry6: Berry @@ Blue = wire[Berry].taggedWith[Black with Blue]
```

would that work for you?

**Comment by joprice** [comment]
That looks good.
